### ISSUE TITLE
Package.loadSettings is deprecated with v0.189

### ISSUE THREAD

**Issue by Bendraneu** [atuttle/atom-language-cfml#15] opened 2015-04-03 17:43 UTC
Store package settings files in the `settings/` directory instead of `scoped-properties/`
```
Package.loadSettings (/Applications/Atom.app/Contents/Resources/app/src/package.js:565:9)
<unknown> (/Applications/Atom.app/Contents/Resources/app/src/package.js:187:43)
```

**Comment by seancoyne** [comment] 2015-04-03 17:44
duplicate of #14

**Closed by seancoyne** 2015-04-03 17:44 UTC
