### ISSUE TITLE
Failed to activate the language-cfml package

### ISSUE THREAD

**Issue by we3geeks** [atuttle/atom-language-cfml#33] opened 2015-07-07 03:30 UTC
Immediately after updating to 0.8.1, language-cfml generated the following:

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.4
**Thrown From**: [language-cfml](https://github.com/atuttle/atom-language-cfml) package, v0.8.1
### Stack Trace

Failed to activate the language-cfml package

```
At Cannot read property 'endsWith' of undefined

TypeError: Cannot read property 'endsWith' of undefined
    at Object.module.exports.activate (/Users/ron/.atom/packages/language-cfml/lib/languageCFML.js:14:23)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:306:60
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:53:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
```
### Commands

```
     -0:10 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-solarized-light-syntax.theme-one-light-ui)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "solarized-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
emmet, v2.3.12
language-cfml, v0.8.1

# Dev
No dev packages
```

**Comment by adeleusiere** [comment] 2015-07-07 09:16
Atom Version: 1.0.0
System: Mac OS X 10.10.4
Having the same issue, with this stack trace:
TypeError: Cannot read property 'scopeName' of undefined
  at TokenizedBuffer.module.exports.TokenizedBuffer.setGrammar (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:130:30)
  at DisplayBuffer.module.exports.DisplayBuffer.setGrammar (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1151:35)
  at TextEditor.module.exports.TextEditor.setGrammar (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2264:33)
  at checkCfscriptEditorGrammar (/Users/aurelien/.atom/packages/language-cfml/lib/languageCFML.js:32:13)
  at Object.module.exports.activate (/Users/aurelien/.atom/packages/language-cfml/lib/languageCFML.js:16:5)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:306:60
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:53:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

**Comment by David-Polehonski** [comment] 2015-07-07 11:36
This issue is caused by a race condition whereby the grammars aren't loaded before the activate function is called.

**Comment by atuttle** [comment] 2015-07-07 12:57
Published 0.8.2 with David's PR. Let us know if that works.

**Comment by KevinMcCoy** [comment] 2015-07-07 13:41
Got it, thanks!!!

**Comment by KevinMcCoy** [comment] 2015-07-07 15:24
However, not sure what going on here...  I know cfml and color coding isn't perfect, for sometime there special char causing the color to mess up.  That aside, looking at this file which is pretty basic, the color is not matching up. 
<img width="532" alt="screen shot 2015-07-07 at 11 22 02 am" src="https://cloud.githubusercontent.com/assets/2472738/8549740/6a87289a-249a-11e5-8891-bbc35981f182.png">

**Comment by dajester2013** [comment] 2015-07-07 15:24
The PR only fixed one of the errors... Apparently the editor's URI can be null, I'm prepping a PR for that.

**Comment by dajester2013** [comment] 2015-07-07 15:26
@David-Polehonski Is there a particular reason that text.html.basic cannot just be put back into cfml.cson and html-cfml.cson be dropped? I think that is why the coloring is off for @KevinMcCoy

**Comment by David-Polehonski** [comment] 2015-07-07 15:51
@dajester2013 @KevinMcCoy - see comment on #35

**Comment by we3geeks** [comment] 2015-07-09 11:31
Showed up again immediately after updating to 0.8.5

Cannot read property 'endsWith' of undefined
Hide Stack Trace
TypeError: Cannot read property 'endsWith' of undefined
    at Object.module.exports.activate (/Users/ron/.atom/packages/language-cfml/lib/languageCFML.js:14:23)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:306:60
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:53:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:227:18

**Comment by dajester2013** [comment] 2015-07-09 12:12
This happened as soon as the package finished updating? 

The line number referred to in the stack trace is not where that method is called. Could you look at the dev tools under sources,  and check the contents of languageCFML.js and see if it matches with the latest version?

Also, what tabs did you have open when it threw the error?

**Comment by we3geeks** [comment] 2015-07-09 12:16
@dajester2013 Yes, immediately after updating. Only tabs open were an empty, untitled tab and the Settings/Updates tab. I will check the languageCFML.js file this evening when I have access to that system again.

**Comment by tollus** [comment] 2015-07-09 12:50
The same problem happened to me. I just quit and reloaded Atom and that resolved it. I think something didn't properly reload when the package was updated for me.

**Comment by stephengfriend** [comment] 2015-07-09 12:55
I also got the same thing immediately after updating a few days ago. Updated to Atom 1.0.1 this morning and then updated language-cfml to 0.8.5 and got the same issue.

[Enter steps to reproduce below:]

1. Updated to Atom 1.0.1
2. Updated to language-cfml 0.8.5

**Atom Version**: 1.0.1
**System**: Mac OS X 10.10.4
**Thrown From**: [language-cfml](https://github.com/atuttle/atom-language-cfml) package, v0.8.5


### Stack Trace

Failed to activate the language-cfml package

```
At Cannot read property 'endsWith' of undefined

TypeError: Cannot read property 'endsWith' of undefined
  at Object.module.exports.activate (/Users/intrikit/.atom/packages/language-cfml/lib/languageCFML.js:23:23)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:312:60
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:59:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
     -0:27.6.0 window:update-available (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-monokai.theme-seti-ui)
     -0:24.6.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-monokai.theme-seti-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "atom-monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
atom-monokai, v0.8.0
atom-pair, v1.1.6
color-picker, v2.0.9
editorconfig, v1.0.1
emmet, v2.3.12
git-diff-details, v0.18.0
git-tab-status, v1.9.2
language-cfml, v0.8.5
language-protobuf, v0.5.0
linter-csslint, v0.0.14
linter-jshint, v0.1.7
linter-tslint, v0.2.3
seti-ui, v0.7.1

# Dev
No dev packages
```

=

**Comment by atuttle** [comment] 2015-07-09 15:14
Please try the latest version and report back if this fixes it

**Comment by stephengfriend** [comment] 2015-07-09 15:27
@atuttle Updated to 0.8.6 with no issue in Atom 1.0.1 :+1:

**Comment by philcruz** [comment] 2017-08-08 20:27
I just updated Atom to v1.19.0 and it gave me this error with a link to this issue

https://www.screencast.com/t/c7ZOcgYQ7qEB

Any ideas?

**Comment by David-Polehonski** [comment] 2017-08-09 13:05
The Function for switching the grammar between script and tag syntax for a cfc uses a legacy property which needs replacing with the appropriate method. Fixed locally and will send a pull request soon.

**Comment by jojoserquina** [comment] 2017-08-10 13:07
Having the same issue... awaiting fix. Thanks!

**Comment by jdjodrey** [comment] 2017-08-10 13:20
Same issue here.

**Comment by jinglesthula** [comment] 2017-08-14 14:17
The error I kept getting over the last week or so that had a link to this issue appears to be resolved with the latest version.  Thanks!

**Comment by atuttle** [comment] 2017-08-17 19:46
@David-Polehonski this was fixed in #105 right? @jojoserquina @jdjodrey @jinglesthula Please make sure you're on the latest **Atom** and latest **atom-language-cfml** (0.17.1 at this time) and report back if you're still having issues.

**Comment by David-Polehonski** [comment] 2017-11-03 15:40
@atuttle Shall We close this again? It seems to be re-resolved.

**Comment by atuttle** [comment] 2017-11-03 22:10
Fine by me

**Closed by atuttle** 2017-11-03 22:10 UTC
