### ISSUE TITLE
question about tag matching

### ISSUE THREAD

**Issue by srconklin** [atuttle/atom-language-cfml#62] opened 2015-11-05 18:14 UTC
not sure if this is the proper forum to ask a question, but I have searched high and low for answer as to how to get tag highlighting turned on for CFML tags in atom. This works nicely ST3.. 
(see screenshot  of what i mean
http://www.evernote.com/shard/s349/sh/2ee21b1c-e296-4c80-b6b7-86b247bd04e2/d2a8c36156d179fa64ff4ac7041fb3e6) 

I thought it might be the atom/bracket-matcher package but from what i can tell it is not. 
This feature is a must for me.
any pointers would be appreciated.
Thanks

UPDATE:

I just noticed that it seems to work when I put my cursor on the closing tag eg: </cfif> but not on the opening one? is this by design? 

UPDATE

Sorry to blow up this post... but it seems it is working for most tags... on start and close : cflock, cfloop, etc...just not the start tag of a cfif..  finding the matching closing </cfif>  seems more useful than the other way around

**Comment by elpete** [comment] 2015-11-05 22:59
<img width="1013" alt="untitled_-__users_eric_peterson_code_github_pull-requests_atom-language-cfml_-_atom" src="https://cloud.githubusercontent.com/assets/2583646/10984341/e929ef3a-83d5-11e5-849c-15aa8638b70b.png">

Is this what you are talking about?  I see it on the latest version of Atom (1.1.0)

**Comment by srconklin** [comment] 2015-11-05 23:24
Yes, but if you add content inside of the CFIF it no longer works
<cfif x eq y>

</cfif>

I have since learned that you must put your cursor before the opening bracket of the cfif then it works, but not on it. then it does not highlight

**Comment by elpete** [comment] 2015-11-06 15:24
Hmmm...can you post your example code that causes the issue?  I'm not seeing it.

Also, you might want to try with some of your packages disabled to see if that helps.

**Comment by srconklin** [comment] 2015-11-06 17:03
@elpete 
here you go.. Is this enough?. I just simply created a new .cfm file to show the issue that i see

1) https://www.evernote.com/shard/s349/sh/b1ba1b34-cfb5-49f5-8a89-10147c888fc1/692c865c6e8d84ff98f296148d54906b

2) https://www.evernote.com/shard/s349/sh/cc071d45-e0d3-40b1-a477-b9bf10300aee/9df5dac4f309d5c02d4104164de5d96d

3) https://www.evernote.com/shard/s349/sh/0b00217a-f6b8-4efd-b8b3-5025b59dbac8/6d4c44f99f0bdfe542910fd7d0fb5417

**Comment by atuttle** [comment] 2015-11-06 18:02
@srconklin just btw, you can paste screen shots right from your clipboard into the github comment box, and the images will be embedded instead of links. :+1:

**Comment by elpete** [comment] 2015-11-06 18:43
Interesting.  I see the problem now.

To recreate it:
```html
<cfif>

</cfif>
```
works.
```html
<cfml x eq y>

</cfml>
```
does not.

Also,
```html
<cfml foo="bar">

</cfml>
```
does not work, while
```html
<cfdocument name="test">

</cfdocument>
```

I can't say at this point if it is a grammar issue or not, but at least the problem is documented.

**Comment by srconklin** [comment] 2015-11-06 18:54
Interestingly it also works if you put your cursor just before the closing bracket and after the 'y' in this example
<cfif x eq y>

**Comment by elpete** [comment] 2015-11-06 19:01
It's definitely a bug.  I think the next step is to track down where Atom is inserting that line.  You would think you could see it in the styling, but....I can't find it yet.  More digging is needed.

**Comment by elpete** [comment] 2015-11-06 19:06
Maybe check out https://github.com/atom/bracket-matcher?

**Comment by srconklin** [comment] 2015-11-06 19:25
I have that installed.. That is not a core package of atom 1.0+

**Comment by elpete** [comment] 2015-11-06 19:29
Didn't even check that.  Sorry.  Probably not the issue then.

> On Nov 6 2015, at 12:25 pm, Scott Conklin &lt;notifications@github.com&gt;
wrote:  

>

> I have that installed.. That is not a core package of atom 1.0+

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/atuttle
/atom-language-cfml/issues/62#issuecomment-154508563).![](https://github.com/n
otifications/beacon/ACdsXu6XWlw-a6qxm2UtNgwbjaow4gOAks5pDPYPgaJpZM4Gc054.gif)

**Comment by elpete** [comment] 2015-11-30 22:54
@srconklin Were you ever able to (a) resolve your issue or (b) figure out the cause?

**Comment by elpete** [comment] 2015-12-16 20:37
Closing this issue.

Not sure if this really fits the scope of the project.
Not getting a response back in any case.
(We can always reopen it if needed. 😊)

**Closed by elpete** 2015-12-16 20:37 UTC
