### ISSUE TITLE
Freezes Atom

### ISSUE THREAD

**Issue by PwrSrg** [atuttle/atom-language-cfml#86] opened 2016-06-02 17:35 UTC
When I have this enabled and have previously opened .cfm files and launch Atom, it completely freezes.  It might be conflicting with another package, but have not had time to debug it.

**Comment by begin-again** [comment] 2017-08-15 17:49
I have experienced this same issue today with Atom 1.19.1. Disabled the package and the problem went away. Then tried the other CF  language package [language-coldfusion](https://atom.io/packages/language-coldfusion) package and had the same problem.  ☹️

**Comment by atuttle** [comment] 2017-08-17 21:50
Based on the [commit history](https://github.com/rwatts3/atom-language-coldfusion/commits/master) I would say that [@rwatts3/atom-language-coldfusion](https://github.com/rwatts3/atom-language-coldfusion) is probably a worse choice than this project. They both started from the same origin (converted from TextMate bundles) but this one has had [numerous contributions](https://github.com/atuttle/atom-language-cfml/pulls?q=is%3Apr+is%3Aclosed) to improve upon that base, whereas [@rwatts3/atom-language-coldfusion](https://github.com/rwatts3/atom-language-coldfusion) has not. No offense intended to @rwatts3!

---

I am inclined to say that this may just be a problem with Atom. I had to force quit it and go back to Sublime to finish out my day today, after I ran a git merge in the terminal which resulted in a conflict involving dozens of files, including some really large ones, and Atom became unresponsive (even after a restart). I equally suspect the new git integration (right sidebar) and this project (atom-language-cfml).

I welcome all contributions to try and resolve this issue, but I will point you to [this new section of the readme that I've just added](https://github.com/atuttle/atom-language-cfml/blob/master/README.md#shepherding-only) because I seem to have to explain (what it says) a lot.

**Comment by David-Polehonski** [comment] 2017-11-03 16:09
Seeing as there doensn't seem to be any further input on the cause of the issue, nor anything pinpointing it specifically to this project shall we close this ticket?

**Comment by rwatts3** [comment] 2017-11-03 17:02
I agree . My project was originally intended to be a quick solution for cfml I actually used it locally for several months prior to releasing it to atom.  I work in an environment where I primarily use node but occasionally have to support a few legacy cf clients. At the time I converted it from text mate I was unaware of this project otherwise I am almost certain I would have used this one instead.  I also agree there are probably far better packages out there now for cfml in atom.

**Closed** 2017-11-03 22:13 UTC
