### ISSUE TITLE
Syntax highlighting breaks for cfcomponent tags with the word ' interface' in an attribute string

### ISSUE THREAD

**Issue by sheenjustin** [atuttle/atom-language-cfml#65] opened 2015-11-25 15:01 UTC
Breaking: 
![cfcomponentsyntaxfailing](https://cloud.githubusercontent.com/assets/9502174/11400398/29eebb92-935b-11e5-91ca-205b7f5e6719.PNG)

Non-breaking: 
![cfcomponentsyntaxpassing](https://cloud.githubusercontent.com/assets/9502174/11400443/6dabf976-935b-11e5-9aa7-fabd3556253e.PNG)

Edit: The word ' interface' doesn't even have to be in an attribute string.
Breaking:
![alsofailing](https://cloud.githubusercontent.com/assets/9502174/11400615/5bafd052-935c-11e5-9dea-426676ad9ce4.png)

Non-breaking:
![alsopassing2](https://cloud.githubusercontent.com/assets/9502174/11400627/725fe332-935c-11e5-9cb5-24a8a8870051.PNG)

Also Non-breaking: 
![alsopassing](https://cloud.githubusercontent.com/assets/9502174/11400588/2f89aade-935c-11e5-80cf-8aee4f2ef57b.PNG)

**Comment by elpete** [comment] 2015-11-25 15:13
Hi, @sheenjustin.  A few clarifying questions for you:

What version of Atom are you running? (Find your version in Menu -> Atom -> About Atom) (Current version is 1.2.4)
What syntax is currently being used? (Bottom right corner.  Something like `cfml`.)
What version of `atom-language-cfml` are you using?  (Current version is 0.10.0)

Thanks!

**Comment by sheenjustin** [comment] 2015-11-25 15:28
He @elpete, I was running 1.0.19 but the problem persisted after upgrading to 1.2.4. I'm also on the latest version of atom-language-cfml, 0.10.0.

The syntax that is used is cfscript, and I'm unable to change out of that syntax to either cfml or html(cfml). After a cursory glance at the grammar files, I think the problem is coming from cfscript.cson, line 26. It's doing a match for interface and assigns the tag to the script syntax. At least, that's what my understanding of the code is. I'm not super familiar with cson.

**Comment by elpete** [comment] 2015-11-25 15:41
Using tags like you are, `cfscript` is not the right grammar.  If you click on the grammar name in the bottom right corner you should be able to search for `CFML` (*not* `HTML (CFML)`).

Can you try that and let us know if that fixes your issue?

**Comment by elpete** [comment] 2015-11-30 22:55
@sheenjustin Did you have a chance to use the `cfml` grammar for this?  Did that fix your issue?

**Comment by elpete** [comment] 2015-12-16 20:36
Closing this issue as we couldn't reproduce it.

**Closed by elpete** 2015-12-16 20:36 UTC
