### ISSUE TITLE
Syntax Highlighting not working in CFCs

### ISSUE THREAD

**Issue by kmac720** [atuttle/atom-language-cfml#110] opened 2018-02-14 04:00 UTC
I'm having an issue with syntax highlighting only working in .cfm files, but not in .cfc files. If I disable lanugage-cfml then the .cfcs immediately highlight properly, but .cfm files are then not highlighted.

**Comment by am2605** [comment] 2018-02-14 04:01
I'm about to push a pull request for this - standby

**Comment by kmac720** [comment] 2018-02-14 04:03
Awesome, thank you!!

**Comment by am2605** [comment] 2018-02-14 06:53
Unfortunately my pull request hasn’t resolved it.  The workaround for the moment is downgrade Atom to 1.23.x

Further discussion of this in #109

**Comment by kmac720** [comment] 2018-02-14 12:34
Any idea when the fix will be pushed out as an update?

**Comment by kmac720** [comment] 2018-02-14 12:37
Okay, thanks.

**Comment by Miguel-F** [comment] 2018-02-14 15:38
I am experiencing this issue as well as [the scrolling issue](#114).  On the scrolling issue, it will not allow you to scroll down beyond the current cursor position when using the mouse scroll wheel.  Using the keyboard (page-up/page-down, arrows) does seem to work normally.

**Comment by Miguel-F** [comment] 2018-02-15 18:04
@atuttle just FYI - this issue can be closed as well with the latest version release. #115 
Thanks.

**Comment by jinglesthula** [comment] 2018-02-16 18:33
On Atom 1.24.0 with 0.18.0 of this package I still see the issue (no highlighting in pure cfscript cfcs; works great in cfm and in cfcs that are CFML and have cfscript tags in them, though).

**Comment by am2605** [comment] 2018-02-18 02:10
Have you restarted Atom to see if that helps?  I did notice the same thing when I upgraded but it seemed to come right after a restart.

**Comment by notronwest** [comment] 2018-02-18 15:42
I am still seeing the issue (Atom 1.24.0) - even after a restart

**Comment by David-Polehonski** [comment] 2018-02-19 10:50
Hi, to help me out in fixing this can I have the following:

- Atom version
- atom-language-cfml package version
- An example cfc against which to test

Also can you confirm that the issue is the syntax highlighting and not the autodetection? Try manually selecting cfscript and seeing if that triggers the highlighting/ and whether is successfully selects cfscript when opening an script based cfc in a new buffer/editor.

Many thanks in advance, once I have a reply I'll start working on a patch.

**Comment by notronwest** [comment] 2018-02-20 00:26
Hi David,

Thank you for looking into this.

I am using Atom version 1.24.0, atom-language-cfml version 0.18.0 and I
have attached a CFC that can be used to test the issue.

The problem seems to be with it not recognizing the CFC as a cfscript. When
I select cfscript syntax the color coding appears. However, opening new
cfc's does not trigger them to be recognized as cfscript.

Hope that helps.

**Comment by David-Polehonski** [comment] 2018-02-20 09:44
Sorry to be a pain, but it seems that github hasn't accepted the attachment. I can review the code, but I'll need an example to be more specific.

**Comment by am2605** [comment] 2018-02-20 09:50
I think you’ll need to attach the file from the GitHub web site - it looks
like it won’t accept an attachment via email

> --
Sent from Gmail Mobile

**Comment by David-Polehonski** [comment] 2018-02-20 10:59
I did some testing on the loading of CFCs, there is a race condition which conflicts with the auto detection if the grammars complete loading before the modules grammar load event listener. I'm submitting a pull request to fix this and update the detection to a slightly lower latency script-first approach; it's easier to presume the cfc is script based unless the first line of non-zero length begins with  a tag.

**Comment by robertdmunn** [comment] 2018-02-20 17:26
I am seeing this issue as well. If anyone else needs a workaround until it is resolved, I think I found one. Disable the language-cfml package and quit Atom. Restart Atom, then enable the language-cfml package. Open a CFC and see if you get syntax highlighting. That seems to be working for me right now.

**Comment by mafimo** [comment] 2018-02-20 21:58
> Disable the language-cfml package and quit Atom. Restart Atom, then enable the language-cfml package.

doing this seemed to work for me

**Comment by notronwest** [comment] 2018-02-21 00:01
That worked for me - thanks!

**Comment by jinglesthula** [comment] 2018-02-23 22:11
@robertdmunn or anyone else who's tried the workaround, can you get the problem to still happen after doing this ever?  e.g. if it's a race condition, can it still affect files once in a while?

**Comment by notronwest** [comment] 2018-02-23 22:56
The only thing I have seen is an Atom crash which caused the problem to
occur again. Disabling and Re-enabling fixes it again.

**Comment by robertdmunn** [comment] 2018-02-23 23:40
I just got it to happen again today. Not sure if it was a crash or what did it, but like @notronwest said, disabling, restarting and re-enabling fixes it again.

**Comment by David-Polehonski** [comment] 2018-02-26 15:07
I've opened a second pull request, building on my first resolving this issue and a number of others. Hopefully one of them will be merged soon and resolve this.

**Closed** 2018-06-25 17:18 UTC
