### ISSUE TITLE
Components with extends that contain dashes or underscores breaks highlighting

### ISSUE THREAD

**Issue by rayfaddis** [atuttle/atom-language-cfml#82] opened 2016-04-14 14:16 UTC
**Atom version:** 1.6.2 and 1.7.0 (was also happening in earlier versions, I do not have specifics on those version numbers anymore)
**Language CFML package version:** 0.12.0

![test_cfc_ __users_rayfaddis_sites_interfolio_core](https://cloud.githubusercontent.com/assets/1969780/14531051/c1de98ea-0229-11e6-97ea-a302cb8a35b3.png)

Example doesn't show though if there are also any underscores it generates the same result.

**Comment by David-Polehonski** [comment] 2017-11-03 16:11
Is this issue resolved? I can't reproduce it, Shall we close this issue?

**Comment by atuttle** [comment] 2017-11-03 22:11
Closing because I'm sitting in a hotel room with nothing better to do before dinner than tidy issues, but if it's still an issue @rayfaddis please do speak up!

**Closed by atuttle** 2017-11-03 22:11 UTC

**Comment by rayfaddis** [comment] 2017-11-07 19:58
@David-Polehonski @atuttle this is resolved for me as well. I'm not in CF as much these days but did some small tests to confirm. I completely missed this not being an issue for me anymore or the PR being opened to fix this. Thanks to everyone.
