### ISSUE TITLE
Package.loadSettings is deprecated.

### ISSUE THREAD

**Issue by mavelar** [atuttle/atom-language-cfml#18] opened 2015-04-12 03:06 UTC
Store package settings files in the `settings/` directory instead of `scoped-properties/`
```
Package.loadSettings (C:\Users\mavelar\AppData\Local\atom\app-0.190.0\resources\app\src\package.js:550:9)
<unknown> (C:\Users\mavelar\AppData\Local\atom\app-0.190.0\resources\app\src\package.js:172:43)
```

**Comment by seancoyne** [comment] 2015-04-13 00:38
duplicate of #14

**Closed by seancoyne** 2015-04-13 00:38 UTC
